# -*- coding: utf-8 -*-
"""tSNE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W0RE-JWWTSo7zbbJWfwE4egn3Ffg_u2K
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from sklearn.manifold import TSNE


iris = load_iris()
X = iris.data
y = iris.target

tsne = TSNE(n_components=2, random_state=42, perplexity=30, n_iter=1000)
X_tsne = tsne.fit_transform(X)


plt.figure(figsize=(8, 6))
plt.scatter(X_tsne[:, 0], X_tsne[:, 1], c=y, cmap='viridis', edgecolor='k', s=50)
plt.title("t-SNE Visualization of the Iris Dataset")
plt.xlabel("t-SNE Component 1")
plt.ylabel("t-SNE Component 2")
plt.colorbar(label="Target Classes")
plt.show()